export const LOG_SOURCE_SIGNATURES: ReadonlyArray<
  readonly [source: string, markers: readonly string[]]
> = [
  ['vitest', ['vitest']],
  ['jest', ['jest']],
  ['mocha', ['mocha']],
  ['ava', ['ava test']],
  ['tap', ['tap version', 'node-tap']],
  ['node-test-runner', ['node:test']],
  ['cypress', ['cypress']],
  ['playwright', ['playwright']],
  ['storybook', ['storybook']],
  ['karma', ['karma']],
  ['webpack', ['webpack']],
  ['vite', ['vite']],
  ['rollup', ['rollup']],
  ['esbuild', ['esbuild']],
  ['babel', ['babel']],
  ['swc', ['swc']],
  ['typescript', ['typescript', 'tsc', 'ts2322', 'ts18048']],
  ['eslint', ['eslint']],
  ['prettier', ['prettier']],
  ['rome', ['rome']],
  ['npm', ['npm err!', 'npm warn', 'npm run']],
  ['pnpm', ['pnpm err!', 'pnpm']],
  ['yarn', ['yarn error', 'yarn run']],
  ['bun', ['bun install', 'bun run']],
  ['nx', ['nx ']],
  ['turborepo', ['turbo run', 'turborepo']],
  ['lerna', ['lerna']],
  ['pytest', ['pytest', 'tests/', 'assertionerror: assert']],
  ['keploy', ['keploy']],
  ['testkube', ['testkube']],
  ['python-unittest', ['unittest', 'ran ', 'failed (failures=']],
  ['tox', ['tox -e', 'tox:']],
  ['nox', ['nox >']],
  ['pip', ['pip install', 'pip uninstall']],
  ['pipenv', ['pipenv']],
  ['poetry', ['poetry install', 'poetry lock']],
  ['uv', ['uv pip', 'astral uv']],
  ['django', ['django', 'manage.py']],
  ['flask', ['flask app']],
  ['fastapi', ['fastapi', 'uvicorn']],
  ['gunicorn', ['gunicorn']],
  ['uvicorn', ['uvicorn']],
  ['celery', ['celery']],
  ['airflow', ['airflow']],
  ['maven', ['maven', 'mvn ', 'mojofailureexception']],
  ['gradle', ['gradle', 'task :', 'build failed with an exception']],
  ['bazel', ['bazel', 'build did not complete successfully']],
  ['cmake', ['cmake error', 'cmakefiles']],
  ['ninja-build', ['ninja: build stopped']],
  ['sbt', ['sbt compile', 'sbt run', 'sbt test', 'sbt publish', 'sbt update', '[sbt]']],
  ['ant', ['apache ant', 'build.xml']],
  ['junit', ['junit']],
  ['spring-boot', ['spring', 'springboot']],
  ['logback', ['logback']],
  ['go-test', ['go test', '--- fail:']],
  ['go-build', ['go build', 'go: downloading']],
  ['golangci-lint', ['golangci-lint']],
  ['gin', ['gin-gonic']],
  ['cobra', ['spf13/cobra']],
  ['cargo', ['cargo build', 'cargo test']],
  ['rustc', ['rustc', 'error[e']],
  ['clippy', ['clippy']],
  ['actix', ['actix']],
  ['tokio', ['tokio']],
  ['dotnet', ['dotnet ', 'asp.net']],
  ['msbuild', ['msbuild', 'error msb']],
  ['nuget', ['nuget']],
  ['xunit', ['xunit']],
  ['nunit', ['nunit']],
  ['serilog', ['serilog']],
  ['phpunit', ['phpunit']],
  ['composer', ['composer']],
  ['laravel', ['laravel']],
  ['symfony', ['symfony']],
  ['bundler', ['bundle install', 'bundler']],
  ['rspec', ['rspec']],
  ['rails', ['rails']],
  ['sidekiq', ['sidekiq']],
  ['docker', ['docker', 'dockerfile']],
  ['buildkit', ['buildkit', '#0 [internal]']],
  ['docker-compose', ['docker-compose', 'compose']],
  ['podman', ['podman']],
  ['containerd', ['containerd']],
  ['runc', ['runc']],
  ['kubernetes', ['kubernetes', 'kubectl', 'k8s']],
  ['kubelet', ['kubelet']],
  ['helm', ['helm']],
  ['kustomize', ['kustomize']],
  ['skaffold', ['skaffold']],
  ['tilt', ['tilt up', 'tiltfile']],
  ['openshift', ['openshift', 'oc ']],
  ['concourse', ['concourse', 'fly -t']],
  ['werf', ['werf']],
  ['nomad', ['hashicorp nomad', 'nomad']],
  ['consul', ['hashicorp consul', 'consul']],
  ['istio', ['istio']],
  ['linkerd', ['linkerd']],
  ['cilium', ['cilium']],
  ['calico', ['calico']],
  ['keda', ['keda']],
  ['knative', ['knative']],
  ['openfaas', ['openfaas']],
  ['cert-manager', ['cert-manager', 'cert manager']],
  ['external-dns', ['external-dns', 'external dns']],
  ['sealed-secrets', ['sealed-secrets', 'sealed secrets']],
  ['kyverno', ['kyverno']],
  ['opa-gatekeeper', ['gatekeeper', 'opa gatekeeper']],
  ['argo-rollouts', ['argo rollouts', 'argo-rollouts']],
  ['flagger', ['flagger']],
  ['crossplane', ['crossplane']],
  ['telepresence', ['telepresence']],
  ['k9s', ['k9s']],
  ['stern', ['stern']],
  ['kubescape', ['kubescape']],
  ['tracetest', ['tracetest']],
  ['polaris', ['fairwinds polaris', 'polaris audit']],
  ['kube-bench', ['kube-bench']],
  ['kube-hunter', ['kube-hunter', 'kube hunter']],
  ['envoy', ['envoy']],
  ['github-actions', ['github actions', '##[error]', '::error::']],
  ['gitlab-ci', ['gitlab-ci', 'running with gitlab-runner']],
  ['jenkins', ['jenkins', '[pipeline]']],
  ['argocd', ['argocd', 'argo cd']],
  ['fluxcd', ['fluxcd', 'flux cd']],
  ['renovate', ['renovate bot', 'renovate']],
  ['circleci', ['circleci']],
  ['travis-ci', ['travis ci', 'travis build']],
  ['azure-pipelines', ['azure pipelines', '##vso']],
  ['teamcity', ['teamcity', '##teamcity']],
  ['buildkite', ['buildkite']],
  ['spinnaker', ['spinnaker']],
  ['harness', ['harness']],
  ['armory', ['armory']],
  ['bamboo', ['atlassian bamboo', 'bamboo build']],
  ['appveyor', ['appveyor']],
  ['codefresh', ['codefresh']],
  ['octopus-deploy', ['octopus deploy', 'octopus']],
  ['drone-ci', ['drone.io', 'drone ci']],
  ['tekton', ['tekton', 'taskrun', 'pipelinerun']],
  ['argo-workflows', ['argo workflows', 'workflow failed']],
  ['trivy', ['trivy', 'vulnerability', 'cve-']],
  ['snyk', ['snyk']],
  ['grype', ['grype']],
  ['semgrep', ['semgrep']],
  ['gitleaks', ['gitleaks']],
  ['dependabot', ['dependabot']],
  ['npm-audit', ['npm audit']],
  ['osv-scanner', ['osv-scanner']],
  ['checkov', ['checkov']],
  ['bandit', ['bandit']],
  ['sonarqube', ['sonarqube', 'sonar']],
  ['nginx', ['nginx']],
  ['apache-httpd', ['apache', 'httpd']],
  ['caddy', ['caddy']],
  ['varnish', ['varnish']],
  ['traefik', ['traefik']],
  ['haproxy', ['haproxy']],
  ['postgresql', ['postgres', 'postgresql']],
  ['mysql', ['mysql']],
  ['mariadb', ['mariadb']],
  ['mongodb', ['mongodb', 'mongod']],
  ['redis', ['redis']],
  ['valkey', ['valkey']],
  ['keydb', ['keydb']],
  ['dragonflydb', ['dragonflydb', 'dragonfly']],
  ['memcached', ['memcached']],
  ['aerospike', ['aerospike']],
  ['dynamodb', ['dynamodb']],
  ['cockroachdb', ['cockroachdb']],
  ['scylladb', ['scylladb']],
  ['yugabytedb', ['yugabytedb', 'yugabyte']],
  ['tidb', ['tidb']],
  ['influxdb', ['influxdb']],
  ['timescaledb', ['timescaledb']],
  ['questdb', ['questdb']],
  ['eventstoredb', ['eventstoredb', 'event store db']],
  ['pgbouncer', ['pgbouncer']],
  ['proxysql', ['proxysql']],
  ['vitess', ['vitess']],
  ['cassandra', ['cassandra']],
  ['clickhouse', ['clickhouse']],
  ['opensearch', ['opensearch']],
  ['elasticsearch', ['elasticsearch']],
  ['oracle-db', ['oracle', 'ora-']],
  ['sqlserver', ['sql server', 'mssql']],
  ['db2', ['db2']],
  ['neo4j', ['neo4j']],
  ['kafka', ['kafka']],
  ['aws-kinesis', ['kinesis']],
  ['aws-msk', ['amazon msk', 'aws msk']],
  ['confluent', ['confluent']],
  ['schema-registry', ['schema registry']],
  ['rabbitmq', ['rabbitmq']],
  ['nats', ['nats']],
  ['apache-pulsar', ['pulsar']],
  ['activemq', ['activemq']],
  ['debezium-server', ['debezium server']],
  ['streamsets', ['streamsets']],
  ['bytewax', ['bytewax']],
  ['materialize', ['materialize']],
  ['risingwave', ['risingwave']],
  ['emqx', ['emqx']],
  ['mosquitto', ['mosquitto']],
  ['aws-sqs', ['aws sqs', 'amazon sqs']],
  ['aws-sns', ['aws sns', 'amazon sns']],
  ['gcp-pubsub', ['pub/sub', 'google pubsub', 'gcp pubsub']],
  ['redpanda', ['redpanda']],
  ['zeromq', ['zeromq', '0mq']],
  ['ibm-mq', ['ibm mq', 'websphere mq']],
  ['cloudformation', ['cloudformation']],
  ['cloud-custodian', ['cloud custodian', 'custodian run']],
  ['infracost', ['infracost']],
  ['terraform-cloud', ['terraform cloud']],
  ['terraform-enterprise', ['terraform enterprise']],
  ['terraform', ['terraform']],
  ['terragrunt', ['terragrunt']],
  ['opentofu', ['opentofu']],
  ['atlantis', ['atlantis']],
  ['spacelift', ['spacelift']],
  ['ansible', ['ansible']],
  ['pulumi', ['pulumi']],
  ['packer', ['packer']],
  ['chef', ['chef']],
  ['puppet', ['puppet']],
  ['saltstack', ['saltstack']],
  ['vault', ['vault']],
  ['aws-lambda', ['aws lambda', 'lambda']],
  ['cloudwatch', ['cloudwatch']],
  ['gcp-cloud-run', ['cloud run']],
  ['azure-functions', ['azure functions']],
  ['gcp-cloud-functions', ['cloud functions']],
  ['aws-ecs', ['aws ecs', 'amazon ecs']],
  ['aws-eks', ['aws eks', 'amazon eks']],
  ['aws-fargate', ['fargate']],
  ['aws-cloudfront', ['cloudfront']],
  ['aws-alb', ['application load balancer', 'aws alb']],
  ['aws-api-gateway', ['api gateway', 'execute-api']],
  ['azure-aks', ['azure aks', 'aks cluster']],
  ['azure-app-service', ['azure app service', 'app service']],
  ['gcp-gke', ['google kubernetes engine', 'gke']],
  ['azure-monitor', ['azure monitor']],
  ['cloudflare', ['cloudflare']],
  ['fastly', ['fastly']],
  ['vercel', ['vercel']],
  ['netlify', ['netlify']],
  ['heroku', ['heroku']],
  ['railway', ['railway']],
  ['fly-io', ['fly.io', 'flyctl']],
  ['prometheus', ['prometheus']],
  ['grafana', ['grafana']],
  ['loki', ['loki']],
  ['logstash', ['logstash']],
  ['fluentd', ['fluentd']],
  ['fluent-bit', ['fluent bit', 'fluent-bit']],
  ['graylog', ['graylog']],
  ['splunk', ['splunk']],
  ['kibana', ['kibana']],
  ['zabbix', ['zabbix']],
  ['nagios', ['nagios']],
  ['jaeger', ['jaeger']],
  ['zipkin', ['zipkin']],
  ['honeycomb', ['honeycomb']],
  ['elastic-apm', ['elastic apm']],
  ['datadog', ['datadog']],
  ['newrelic', ['new relic']],
  ['sentry', ['sentry']],
  ['sumologic', ['sumologic']],
  ['logz-io', ['logz.io', 'logz io']],
  ['mezmo', ['mezmo', 'logdna']],
  ['parca', ['parca']],
  ['pixie', ['pixie']],
  ['falco', ['falco']],
  ['aquasec', ['aquasec', 'aqua security']],
  ['wiz', ['wiz']],
  ['tenable', ['tenable']],
  ['prisma-cloud', ['prisma cloud']],
  ['qualys', ['qualys']],
  ['crowdstrike', ['crowdstrike']],
  ['aws-guardduty', ['guardduty']],
  ['aws-security-hub', ['security hub']],
  ['aws-cloudtrail', ['cloudtrail']],
  ['vanta', ['vanta']],
  ['drata', ['drata']],
  ['panther', ['panther']],
  ['falcon-logscale', ['falcon logscale', 'humio']],
  ['owasp-zap', ['owasp zap', 'zap baseline']],
  ['sonatype-nexus', ['sonatype nexus', 'nexus repository']],
  ['jfrog-artifactory', ['artifactory', 'jfrog']],
  ['harbor', ['harbor']],
  ['syslog', ['syslog']],
  ['journald', ['journald', 'systemd']],
  ['hadoop', ['hadoop']],
  ['spark', ['apache spark', 'spark executor']],
  ['flink', ['apache flink', 'flink job']],
  ['kubeflow', ['kubeflow']],
  ['ray', ['ray cluster']],
  ['mlflow', ['mlflow']],
  ['langfuse', ['langfuse']],
  ['langsmith', ['langsmith']],
  ['arize-phoenix', ['arize phoenix', 'phoenix tracing']],
  ['weights-and-biases', ['weights & biases', 'wandb']],
  ['neptune-ai', ['neptune.ai', 'neptune run']],
  ['mlrun', ['mlrun']],
  ['seldon-core', ['seldon core', 'seldon']],
  ['kserve', ['kserve']],
  ['bentoml', ['bentoml']],
  ['triton-inference-server', ['triton inference server', 'nvidia triton']],
  ['feast', ['feast feature store', 'feast apply']],
  ['llamaindex', ['llamaindex']],
  ['haystack', ['deepset haystack', 'haystack pipeline']],
  ['milvus', ['milvus']],
  ['qdrant', ['qdrant']],
  ['weaviate', ['weaviate']],
  ['pinecone', ['pinecone']],
  ['chromadb', ['chromadb', 'chroma db']],
  ['vespa', ['vespa']],
  ['singlestore', ['singlestore', 'memsql']],
  ['dbt', ['dbt run', 'dbt test']],
  ['dagster', ['dagster']],
  ['airbyte', ['airbyte']],
  ['fivetran', ['fivetran']],
  ['stitch-data', ['stitch data']],
  ['kafka-connect', ['kafka connect']],
  ['debezium', ['debezium']],
  ['trino', ['trino']],
  ['presto', ['presto']],
  ['apache-druid', ['apache druid', 'druid coordinator']],
  ['apache-pinot', ['apache pinot', 'pinot controller']],
  ['snowflake', ['snowflake']],
  ['bigquery', ['bigquery']],
  ['redshift', ['redshift']],
  ['azure-synapse', ['azure synapse', 'synapse sql']],
  ['databricks', ['databricks']],
  ['tableau', ['tableau']],
  ['powerbi', ['power bi', 'powerbi']],
  ['metabase', ['metabase']],
  ['superset', ['apache superset', 'superset']],
  ['looker', ['looker']],
  ['qlik', ['qlik']],
  ['mode-analytics', ['mode analytics']],
  ['apache-beam', ['apache beam', 'beam pipeline']],
  ['apache-nifi', ['apache nifi', 'nifi flow']],
  ['meltano', ['meltano']],
  ['hevo-data', ['hevo data']],
  ['matillion', ['matillion']],
  ['talend', ['talend']],
  ['informatica', ['informatica']],
  ['dataform', ['dataform']],
  ['great-expectations', ['great expectations', 'gx checkpoint']],
  ['monte-carlo', ['monte carlo']],
  ['soda-core', ['soda core', 'soda scan']],
  ['apache-hudi', ['apache hudi', 'hudi deltastreamer']],
  ['delta-lake', ['delta lake']],
  ['apache-iceberg', ['apache iceberg', 'iceberg table']],
  ['starrocks', ['starrocks']],
  ['greenplum', ['greenplum']],
  ['teradata', ['teradata']],
  ['supabase', ['supabase']],
  ['firebase', ['firebase']],
  ['hasura', ['hasura']],
  ['gitpod', ['gitpod']],
  ['dynatrace', ['dynatrace']],
  ['appdynamics', ['appdynamics']],
  ['bugsnag', ['bugsnag']],
  ['rollbar', ['rollbar']],
  ['lacework', ['lacework']],
  ['openstack', ['openstack', 'nova', 'neutron']],
  ['oracle-cloud', ['oracle cloud infrastructure', 'oci tenancy']],
  ['alibaba-cloud', ['alibaba cloud', 'aliyun']],
  ['tencent-cloud', ['tencent cloud', 'tke cluster']],
  ['digitalocean', ['digitalocean', 'doctl']],
  ['linode', ['linode']],
  ['minio', ['minio']],
  ['ceph', ['ceph']],
  ['etcd', ['etcd']],
  ['zookeeper', ['zookeeper']],
  ['kong', ['kong gateway', 'kong route']],
  ['apisix', ['apache apisix', 'apisix route']],
  ['keycloak', ['keycloak']],
  ['okta', ['okta']],
  ['auth0', ['auth0']],
  ['launchdarkly', ['launchdarkly']],
  ['unleash', ['unleash']],
  ['splitio', ['split.io', 'splitio']],
  ['flagsmith', ['flagsmith']],
  ['pagerduty', ['pagerduty']],
  ['opsgenie', ['opsgenie']],
  ['victorops', ['victorops']],
  ['statuspage', ['statuspage']],
  ['incident-io', ['incident.io', 'incident io']],
  ['firehydrant', ['firehydrant']],
  ['rootly', ['rootly']],
  ['squadcast', ['squadcast']],
  ['grafana-oncall', ['grafana oncall']],
  ['cloudbees', ['cloudbees']],
  ['jenkins-x', ['jenkins x', 'jenkins-x']],
  ['backstage', ['backstage']],
  ['portainer', ['portainer']],
  ['rancher', ['rancher']],
  ['longhorn', ['longhorn']],
  ['rook-ceph', ['rook-ceph', 'rook ceph']],
  ['temporal', ['temporal']],
  ['prefect', ['prefect']],
  ['camunda', ['camunda']],
  ['zeebe', ['zeebe']],
  ['n8n', ['n8n']],
  ['mulesoft', ['mulesoft']],
  ['boomi', ['boomi']],
  ['apigee', ['apigee']],
  ['gravitee', ['gravitee']],
  ['kong-konnect', ['kong konnect', 'kong-konnect']],
  ['consul-connect', ['consul connect', 'consul-connect']],
  ['boundary', ['hashicorp boundary', 'boundary']],
  ['gremlin', ['gremlin']],
  ['litmuschaos', ['litmuschaos', 'litmus chaos']],
  ['chaos-mesh', ['chaos mesh', 'chaos-mesh']],
  ['steadybit', ['steadybit']],
  ['eventbridge', ['eventbridge']],
  ['aws-step-functions', ['step functions', 'states execution']],
  ['dapr', ['dapr']],
  ['eventarc', ['eventarc']],
  ['workato', ['workato']],
  ['tray-io', ['tray.io', 'tray io']],
  ['k6', ['k6 run', 'k6 cloud']],
  ['gatling', ['gatling']],
  ['locust', ['locust']],
  ['jmeter', ['jmeter']],
  ['artillery', ['artillery']],
  ['vegeta', ['vegeta']],
  ['fortio', ['fortio']],
  ['chaosblade', ['chaosblade']],
  ['salesforce', ['salesforce']],
  ['servicenow', ['servicenow', 'service now']],
  ['jira', ['jira']],
  ['confluence', ['confluence']],
  ['slack', ['slack']],
  ['workday', ['workday']],
  ['netsuite', ['netsuite']],
  ['sap', ['sap']],
  ['zendesk', ['zendesk']],
  ['freshdesk', ['freshdesk']],
  ['hubspot', ['hubspot']],
  ['stripe', ['stripe']],
  ['adyen', ['adyen']],
  ['braintree', ['braintree']],
  ['paypal', ['paypal']],
  ['square', ['square']],
  ['plaid', ['plaid']],
  ['twilio', ['twilio']],
  ['sendgrid', ['sendgrid']],
  ['mailgun', ['mailgun']],
  ['segment', ['segment']],
  ['rudderstack', ['rudderstack']],
  ['opentelemetry', ['opentelemetry', 'otel']],

  // ── Web Frameworks (JS/TS) ──────────────────────────────────────
  ['express', ['express', 'expressjs', 'express server']],
  ['fastify', ['fastify', 'fastify server']],
  ['hapi', ['hapi', '@hapi/hapi']],
  ['koa', ['koa', 'koa server']],
  ['nestjs', ['nestjs', '@nestjs', 'nest.js']],
  ['nextjs', ['next.js', 'nextjs', 'next build', 'next start', 'next dev']],
  ['nuxt', ['nuxt', 'nuxt3', 'nuxt build', 'nuxt generate']],
  ['sveltekit', ['sveltekit', 'svelte kit', 'sveltekit adapter']],
  ['remix', ['remix', '@remix-run', 'remix build']],
  ['astro', ['astro', 'astro build', 'astro dev', 'astro check']],
  ['adonis', ['adonisjs', 'adonis', 'ace make:']],
  ['hono', ['hono', 'honojs', 'hono server']],
  ['deno-runtime', ['deno', 'deno task', 'deno run', 'deno compile']],
  ['elysia', ['elysia', 'elysiajs']],
  ['feathers', ['feathers', 'feathersjs', '@feathersjs']],

  // ── Logging Libraries ────────────────────────────────────────────
  ['pino', ['pino', 'pino pretty', 'pino.info']],
  ['winston', ['winston', 'winston logger']],
  ['bunyan', ['bunyan', 'bunyan logger']],
  ['morgan', ['morgan', 'morgan logger']],
  ['log4js', ['log4js', 'log4js-node']],
  ['log4j', ['log4j', 'org.apache.log4j']],
  ['slf4j', ['slf4j', 'org.slf4j']],
  ['zap-logger', ['zap logger', 'go.uber.org/zap']],
  ['zerolog', ['zerolog', 'rs/zerolog']],
  ['structlog', ['structlog', 'python-structlog']],
  ['loguru', ['loguru', 'loguru.py']],
  ['spdlog', ['spdlog']],

  // ── Mobile Frameworks ────────────────────────────────────────────
  ['react-native', ['react native', 'react-native', 'reactnative']],
  ['flutter', ['flutter', 'flutter test', 'flutter build']],
  ['expo', ['expo', 'expo-cli', 'expo start', 'eas build']],
  ['capacitor', ['capacitor', '@capacitor', 'capacitor run']],
  ['ionic', ['ionic', 'ionic framework', 'ionic cap']],

  // ── Desktop Frameworks ────────────────────────────────────────────
  ['electron', ['electron', 'electron-builder', 'electron-forge']],
  ['tauri', ['tauri', 'tauri app', 'tauri build']],
  ['qt', ['qt framework', 'qwarning', 'qdebug', 'qcritical']],

  // ── CMS Platforms ────────────────────────────────────────────────
  ['wordpress', ['wordpress', 'wp-content', 'wp-admin', 'wp-includes']],
  ['drupal', ['drupal', 'drupal.org']],
  ['strapi', ['strapi', 'strapi start']],
  ['ghost-cms', ['ghost cms', 'ghost blog', 'ghost-cli']],
  ['contentful', ['contentful']],
  ['sanity', ['sanity.io', 'sanity studio', 'sanity start']],
  ['payload', ['payload cms', 'payloadcms', 'payload start']],
  ['directus', ['directus', 'directus start']],
  ['webflow', ['webflow']],

  // ── E-commerce ───────────────────────────────────────────────────
  ['shopify', ['shopify', 'shopify-cli']],
  ['magento', ['magento', 'magento2']],
  ['woocommerce', ['woocommerce']],
  ['bigcommerce', ['bigcommerce']],
  ['medusa', ['medusajs', 'medusa start', 'medusa new']],

  // ── Search Engines ───────────────────────────────────────────────
  ['meilisearch', ['meilisearch', 'meili search', 'meilisearch index']],
  ['typesense', ['typesense', 'typesense server']],
  ['solr', ['solr', 'apache solr', 'solrconfig']],
  ['algolia', ['algolia', 'algolia index']],

  // ── Java App Servers ─────────────────────────────────────────────
  ['tomcat', ['tomcat', 'apache tomcat', 'catalina.start']],
  ['jetty', ['jetty', 'eclipse jetty', 'jetty.server']],
  ['wildfly', ['wildfly', 'jboss', 'jboss-as']],
  ['glassfish', ['glassfish', 'glassfish server']],
  ['websphere', ['websphere', 'ibm websphere', 'was server']],
  ['weblogic', ['weblogic', 'oracle weblogic']],

  // ── Java Frameworks ──────────────────────────────────────────────
  ['micronaut', ['micronaut', 'micronaut startup']],
  ['quarkus', ['quarkus', 'quarkus dev', 'quarkus build']],
  ['vertx', ['vert.x', 'vertx', 'io.vertx']],
  ['helidon', ['helidon', 'helidon se', 'helidon mp']],
  ['jakarta-ee', ['jakarta ee', 'jakarta.ee', 'javax.']],

  // ── Python Lint/Format ──────────────────────────────────────────
  ['ruff', ['ruff', 'ruff check', 'ruff format']],
  ['mypy', ['mypy', 'mypy: error:', 'mypy: warning:']],
  ['pyright', ['pyright', 'pyright -']],
  ['pylint', ['pylint', 'pylint --']],
  ['isort', ['isort', 'isort --']],

  // ── Python Async Frameworks ─────────────────────────────────────
  ['aiohttp', ['aiohttp', 'aiohttp.server']],
  ['sanic', ['sanic', 'sanic server']],
  ['tornado-framework', ['tornado', 'tornado.web']],
  ['twisted', ['twisted', 'twisted.internet']],
  ['scrapy', ['scrapy', 'scrapy crawl', 'scrapy.spider']],

  // ── Go Frameworks ────────────────────────────────────────────────
  ['echo-framework', ['echo lab', 'labstack/echo', 'echo v4']],
  ['fiber', ['fiber', 'gofiber', 'fiber v2']],
  ['chi', ['chi router', 'go-chi', 'chi.middleware']],
  ['buffalo', ['buffalo', 'gobuffalo', 'buffalo dev']],
  ['revel', ['revel', 'revel framework', 'revel run']],
  ['go-kit', ['go-kit', 'go kit', 'go-kit/kit']],
  ['go-micro', ['go-micro', 'go micro', 'micro server']],

  // ── Rust Frameworks ──────────────────────────────────────────────
  ['rocket', ['rocket.rs', 'rocket rust', 'rocket server']],
  ['warp-framework', ['warp filter', 'seanmonstar/warp', 'warp server']],
  ['axum', ['axum', 'tokio-rs/axum', 'axum router']],
  ['tide', ['tide', 'http-rs/tide', 'tide server']],

  // ── Ruby Frameworks ──────────────────────────────────────────────
  ['sinatra', ['sinatra', 'sinatra app']],
  ['hanami', ['hanami', 'hanami server']],
  ['puma', ['puma webserver', 'puma worker', 'puma starting']],
  ['unicorn-rb', ['unicorn worker', 'unicorn master', 'unicorn_rails']],
  ['passenger', ['passenger', 'phusion passenger']],

  // ── ORM / Database Tools ─────────────────────────────────────────
  ['prisma', ['prisma', 'prisma migrate', 'prisma generate', 'prisma db']],
  ['drizzle-orm', ['drizzle-orm', 'drizzle kit', 'drizzle push']],
  ['typeorm', ['typeorm', 'typeorm query', 'typeorm:']],
  ['sequelize', ['sequelize', 'sequelize-cli']],
  ['knex', ['knex', 'knexfile', 'knex migrate']],
  ['flyway', ['flyway', 'flyway migrate', 'flyway validate']],
  ['liquibase', ['liquibase', 'liquibase update']],
  ['alembic', ['alembic', 'alembic upgrade', 'alembic revision']],
  ['sqlalchemy', ['sqlalchemy', 'sqlalchemy.orm']],
  ['mongoose', ['mongoose', 'mongoose:', 'mongoose.connect']],
  ['mikro-orm', ['mikro-orm', 'mikroorm', 'mikro-orm migrate']],
  ['objection', ['objection.js', 'objectionjs']],

  // ── Edge / Serverless Runtimes ────────────────────────────────────
  ['cloudflare-workers', ['cloudflare workers', 'wrangler', 'wrangler dev']],
  ['deno-deploy', ['deno deploy', 'deployctl']],
  ['serverless-framework', ['serverless framework', 'serverless deploy', 'serverless invoke']],
  ['openwhisk', ['openwhisk', 'wsk action']],
  ['nuclio', ['nuclio', 'nuclio function']],

  // ── Real-time / WebSocket ────────────────────────────────────────
  ['socketio', ['socket.io', 'socketio', 'socket.io server']],
  ['pusher', ['pusher', 'pusher channel']],
  ['ably', ['ably', 'ably channel', 'ably realtime']],
  ['livekit', ['livekit', 'livekit-server']],
  ['centrifugo', ['centrifugo', 'centrifugal']],

  // ── GraphQL ──────────────────────────────────────────────────────
  ['apollo-server', ['apollo server', 'apollo-server', 'apollographql']],
  ['graphql-yoga', ['graphql yoga', 'graphql-yoga']],
  ['mercurius', ['mercurius', 'mercurius upload']],
  ['dgraph', ['dgraph', 'dgraph query', 'dgraph ratel']],

  // ── Observability (continued) ────────────────────────────────────
  ['instana', ['instana', 'instana sensor']],
  ['signalfx', ['signalfx', 'signal fx', 'signalfx ingest']],
  ['lightstep', ['lightstep', 'lightstep tracer']],
  ['thanos', ['thanos', 'thanos.io', 'thanos query']],
  ['cortex', ['cortexmetrics', 'cortex metrics', 'cortex ruler']],
  ['victoriametrics', ['victoriametrics', 'victoria metrics', 'vminsert']],
  ['grafana-tempo', ['grafana tempo', 'tempo query', 'tempo-distributor']],

  // ── AI / ML ──────────────────────────────────────────────────────
  ['openai-api', ['openai', 'openai api', 'openai.error']],
  ['huggingface', ['huggingface', 'hugging face', 'huggingface.co']],
  ['ollama', ['ollama', 'ollama run', 'ollama serve']],
  ['vllm', ['vllm', 'vllm serve', 'vllm engine']],
  ['torchserve', ['torchserve', 'torch serve', 'ts torchserve']],
  ['comfyui', ['comfyui', 'comfyui manager']],
  ['stable-diffusion', ['stable diffusion', 'stablediffusion', 'sd-webui']],
  ['deepspeed', ['deepspeed', 'deepspeed runner']],
  ['llama-cpp', ['llama.cpp', 'llama cpp', 'llama-cpp-python']],

  // ── Auth / Identity ──────────────────────────────────────────────
  ['clerk', ['clerk', 'clerk.dev']],
  ['firebase-auth', ['firebase auth', 'firebaseauthentication']],
  ['supabase-auth', ['supabase auth', 'gotrue']],
  ['authelia', ['authelia', 'authelia portal']],
  ['lldap', ['lldap']],
  ['dex-idp', ['dex idp', 'dexidp/dex']],
  ['zitadel', ['zitadel', 'zitadel auth']],

  // ── Secrets / Config Management ──────────────────────────────────
  ['aws-secrets-manager', ['secrets manager', 'aws secretsmanager']],
  ['aws-kms', ['aws kms', 'kms.amazonaws']],
  ['doppler', ['doppler', 'doppler secrets', 'doppler run']],
  ['infisical', ['infisical', 'infisical scan']],
  ['aws-ssm', ['ssm parameter', 'aws ssm', 'amazon ssm']],

  // ── Storage / CDN ────────────────────────────────────────────────
  ['aws-s3', ['s3 bucket', 'aws s3', 'amazon s3', 's3.amazonaws']],
  ['gcs', ['google cloud storage', 'gcs bucket', 'storage.googleapis']],
  ['azure-blob', ['azure blob', 'blob storage', 'blob.core.windows']],
  ['backblaze-b2', ['backblaze b2', 'b2 cloud', 'b2api']],
  ['wasabi', ['wasabi', 'wasabisys']],
  ['akamai', ['akamai', 'akamaihd.net', 'akamai edge']],
  ['imperva', ['imperva', 'imperva waf', 'incapsula']],

  // ── Game Engines ─────────────────────────────────────────────────
  ['unity', ['unity', 'unityengine', 'unityplayer']],
  ['unreal-engine', ['unreal engine', 'unrealengine', 'ue5']],
  ['godot', ['godot engine', 'godot', 'godot project']],
  ['bevy', ['bevy engine', 'bevy', 'bevy_ecs']],

  // ── IoT / Embedded ──────────────────────────────────────────────
  ['platformio', ['platformio', 'platformio.org', 'pio run']],
  ['arduino', ['arduino', 'arduino-cli']],
  ['esphome', ['esphome', 'esphome config']],
  ['home-assistant', ['home assistant', 'homeassistant', 'hassio']],
  ['tasmota', ['tasmota', 'tasmota mqtt']],
  ['openhab', ['openhab', 'openhabian']],

  // ── Networking / VPN ─────────────────────────────────────────────
  ['wireguard', ['wireguard', 'wg0']],
  ['tailscale', ['tailscale', 'tailscale up']],
  ['ngrok', ['ngrok', 'ngrok http']],
  ['cloudflare-tunnel', ['cloudflare tunnel', 'cloudflared']],
  ['zerotier', ['zerotier', 'zerotier-one']],

  // ── Analytics ────────────────────────────────────────────────────
  ['posthog', ['posthog', 'posthog capture']],
  ['amplitude', ['amplitude', 'amplitude identify']],
  ['mixpanel', ['mixpanel', 'mixpanel track']],
  ['heap-analytics', ['heap analytics', 'heap.io', 'heap track']],
  ['plausible', ['plausible', 'plausible analytics']],
  ['matomo', ['matomo', 'piwik']],
  ['countly', ['countly', 'countly server']],

  // ── Email Services ───────────────────────────────────────────────
  ['aws-ses', ['amazon ses', 'aws ses', 'email.amazonaws']],
  ['mailchimp', ['mailchimp', 'mandrill']],
  ['brevo', ['brevo', 'sendinblue']],
  ['postmark', ['postmark', 'postmarkapp']],
  ['resend', ['resend', 'resend.com']],
  ['sparkpost', ['sparkpost', 'sparkpost mail']],

  // ── Databases (more) ────────────────────────────────────────────
  ['surrealdb', ['surrealdb', 'surrealdb start']],
  ['planetscale', ['planetscale', 'pscale', 'planetscale database']],
  ['neon-db', ['neon database', 'neondatabase', 'neon.tech']],
  ['d1-database', ['cloudflare d1', 'd1 database', 'wrangler d1']],
  ['tigerbeetle', ['tigerbeetle', 'tigerbeetle start']],
  ['foundationdb', ['foundationdb', 'foundation db', 'fdbserver']],
  ['apache-geode', ['apache geode', 'geode', 'gfsh']],
  ['orientdb', ['orientdb', 'orientdb server']],
  ['arangodb', ['arangodb', 'arangoimp']],

  // ── Mobile CI/CD ─────────────────────────────────────────────────
  ['bitrise', ['bitrise', 'bitrise.io']],
  ['codemagic', ['codemagic', 'codemagic-cli']],
  ['appcenter', ['app center', 'appcenter', 'appcenter.ms']],
  ['fastlane', ['fastlane', 'fastlane lane']],

  // ── CI/CD (more) ─────────────────────────────────────────────────
  ['dagger', ['dagger', 'dagger.io', 'dagger do']],
  ['woodpecker-ci', ['woodpecker', 'woodpecker-ci', 'woodpecker pipeline']],
  ['agola', ['agola', 'agola run', 'agoladb']],

  // ── Testing (more) ──────────────────────────────────────────────
  ['testcafe', ['testcafe', 'testcafe runner']],
  ['nightwatch', ['nightwatch', 'nightwatchjs', 'nightwatch test']],
  ['webdriverio', ['webdriverio', 'wdio', 'wdio runner']],
  ['selenium', ['selenium', 'selenium webdriver', 'selenium grid']],
  ['cucumber', ['cucumber', 'cucumber-js', 'cucumber test']],
  ['robot-framework', ['robot framework', 'robotframework', 'robot --test']],
  ['behave', ['behave', 'behave bdd']],

  // ── Load Testing (more) ─────────────────────────────────────────
  ['hey', ['rakyll/hey', 'hey -z']],
  ['wrk', ['wg/wrk', 'wrk -t']],

  // ── Documentation ────────────────────────────────────────────────
  ['docusaurus', ['docusaurus', 'docusaurus build', 'docusaurus start']],
  ['mkdocs-material', ['mkdocs-material', 'mkdocs build']],
  ['sphinx', ['sphinx', 'sphinx-build', 'sphinx-autogen']],
  ['mdbook', ['mdbook', 'rust-lang/mdbook', 'mdbook build']],

  // ── Workflow (more) ──────────────────────────────────────────────
  ['kestra', ['kestra', 'kestra flow']],
  ['windmill', ['windmill', 'windmill-dev', 'windmill script']],
  ['inngest', ['inngest', 'inngest function']],
  ['triggerdev', ['trigger.dev', 'triggerdev', 'trigger.dev job']],

  // ── Messaging (more) ────────────────────────────────────────────
  ['bullmq', ['bullmq', 'bull mq', 'bullmq queue']],
  ['bull-redis', ['bull redis', 'bull queue', 'bull.process']],

  // ── Infrastructure (more) ────────────────────────────────────────
  ['aws-cdk', ['aws cdk', 'cdk deploy', 'cdk synth', 'cdk diff']],
  ['cdktf', ['cdktf', 'cdk for terraform', 'cdktf deploy']],
  ['minikube', ['minikube', 'minikube start', 'minikube dashboard']],
  ['kind', ['kind create', 'sigs.k8s.io/kind']],
  ['k3s', ['k3s', 'k3s server', 'k3s agent']],
  ['k3d', ['k3d', 'k3d cluster', 'k3d create']],

  // ── AI Frameworks (continued) ────────────────────────────────────
  ['langchain', ['langchain', 'langchain.py', 'langchain.js']],

  // ── FinOps / Cost ────────────────────────────────────────────────
  ['opencost', ['opencost', 'opencost metrics']],
  ['kubecost', ['kubecost', 'kubecost api']],
  ['aws-cost-explorer', ['cost explorer', 'aws cost']],

  // ── Policy / Governance ──────────────────────────────────────────
  ['opa', ['open policy agent', 'opa eval', 'rego:']],
  ['sentinel', ['sentinel policy', 'hashicorp sentinel']],

  // ── Browser Automation ───────────────────────────────────────────
  ['puppeteer', ['puppeteer', 'puppeteer browser']],
  ['playwright-test', ['playwright test', '@playwright/test']],

  // ── Container Registries (more) ──────────────────────────────────
  ['ecr', ['amazon ecr', 'aws ecr', 'ecr.amazonaws']],
  ['gcr', ['gcr.io', 'google container registry']],
  ['acr', ['azure container registry', 'azurecr.io']],

  // ── Config Management (more) ──────────────────────────────────────
  ['cosign', ['cosign', 'cosign sign', 'cosign verify']],
  ['sbom', ['sbom', 'syft sbom', 'spdx']],
  ['syft', ['syft', 'syft packages']],
  ['scorecard', ['openssf scorecard', 'scorecard', 'oss scorecard']],

  // ── Git Tools ────────────────────────────────────────────────────
  ['gitlab', ['gitlab.com', 'gitlab runner', 'gitlab api']],
  ['bitbucket', ['bitbucket', 'bitbucket-pipelines', 'bitbucket.org']],
  ['pre-commit', ['pre-commit', 'pre-commit run']],
  ['husky', ['husky', 'husky install']],

  // ── Language Runtimes ────────────────────────────────────────────
  ['graalvm', ['graalvm', 'native-image']],
  ['jvm', ['hotspot', 'openjdk', 'java version']],
  ['v8', ['v8 engine', 'v8::']],
  ['cpython', ['cpython', 'python3.1', 'python3.1']],

  // ── Network / DNS ────────────────────────────────────────────────
  ['coredns', ['coredns', 'coredns plugin']],
  ['powerdns', ['powerdns', 'pdns']],
  ['bind9', ['bind9', 'named:', 'isc bind']],

  // ── Service Mesh (more) ──────────────────────────────────────────
  ['aws-app-mesh', ['app mesh', 'aws app mesh']],
  ['consul-service-mesh', ['consul service mesh', 'consul connect proxy']],

  // ── Backup / DR ──────────────────────────────────────────────────
  ['velero', ['velero', 'velero backup', 'velero restore']],
  ['restic', ['restic', 'restic backup', 'restic restore']],
  ['borg', ['borg backup', 'borgmatic']],
];

export const KNOWN_LOG_SOURCES: readonly string[] = LOG_SOURCE_SIGNATURES.map(
  ([source]) => source,
);
